CREATE TABLE loan (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	loan_time varchar(255) NOT NULL,
	user_app varchar(1000) NOT NULL,
	book varchar(1000) NOT NULL,
	loan_specificid varchar(255) NULL,

  CONSTRAINT loan_pkey PRIMARY KEY (id)
);
